version: '3'

services:
  web:
    image: rizkyario/piscine_php_rush00
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "81:80"
    links:
      - db
    volumes:
      - .:/var/www/html/

  db:
    image: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3301:3306"
  #docker-compose up