app:
  image: php:7
  command: php -S 0.0.0.0:8000 /app/public/index.php
  ports:
    - "8000:8000"
  volumes:
    - .:/app

composer:
  image: composer/composer:php7
  command: install
  volumes:
    - .:/app